# Local development profile
# Overrides main config for local development convenience

spring.jpa.hibernate.ddl-auto=update
spring.flyway.enabled=false
spring.jpa.show-sql=true

logging.level.root=DEBUG
logging.level.com.swafy=DEBUG
