name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Execute deployment commands via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Navigate to vamo project directory on the VM
            cd ~/vamo
            
            # Pull the latest changes from the repository
            git pull origin main

            # incase the db schema changed
            # docker compose down -v
            
            # Rebuild the backend image and restart the containers
            docker compose up --build -d
